version: '3.6'
services:
  web:
    build: .
    ports:
      - 5000:5000
    depends_on: 
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: database.conf
    expose: 
      - 5432
volumes:
  # for persistence between restarts
  postgres_data: {}
    